export const FETCH_API = "FETCH_API";
export const FETCH_API_SUCCESS = "FETCH_API_SUCCESS";
export const FETCH_API_FAILURE = "FETCH_API_FAILURE";
export const FETCH_API_PRODUCT = "FETCH_API_PRODUCT";
export const FETCH_API_PRODUCT_SUCCESS = "FETCH_API_PRODUCT_SUCCESS";
export const FETCH_API_STATIC = "FETCH_API_STATIC";
export const FETCH_API_STATIC_REVENUE_SUCCESS =
  "FETCH_API_STATIC_REVENUE_SUCCESS";
export const FETCH_API_STATIC_ACCESSION_SUCCESS =
  "FETCH_API_STATIC_ACCESSION_SUCCESS";
export const FETCH_API_STATIC_NEEDED_SUCCESS =
  "FETCH_API_STATIC_NEEDED_SUCCESS";
