export const FETCH_API = "FETCH_API";
export const FETCH_API_SUCCESS = "FETCH_API_SUCCESS";
export const FETCH_API_FAILURE = "FETCH_API_FAILURE";
export const FETCH_API_PRODUCT = "FETCH_API_PRODUCT";
export const FETCH_API_PRODUCT_SUCCESS = "FETCH_API_PRODUCT_SUCCESS";
export const FETCH_API_STATIC = "FETCH_API_STATIC";
export const FETCH_API_STATIC_REVENUE_SUCCESS =
    "FETCH_API_STATIC_REVENUE_SUCCESS";
export const FETCH_API_STATIC_ACCESSION_SUCCESS =
    "FETCH_API_STATIC_ACCESSION_SUCCESS";
export const FETCH_API_STATIC_NEEDED_SUCCESS =
    "FETCH_API_STATIC_NEEDED_SUCCESS";
export const FETCH_API_ORDER = "FETCH_API_ORDER";
export const FETCH_API_ORDER_SUCCESS = "FETCH_API_ORDER_SUCCESS";
export const FETCH_API_ADVERTISE = "FETCH_API_ADVERTISE";

export const FETCH_API_ADVERTISE_SUCCESS = "FETCH_API_ADVERTISE_SUCCESS";
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS"

